import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/ReduxProvider";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ralli-web app",
  description: "Generated by Ralli team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
